### ISSUE TITLE
Zimwriterfs-docker doesn't work with --redirects=

### ISSUE THREAD

**Issue by dattaz** [openzim/zim-tools#103]
Path of --redirects= should be rewritten with path in Docker ; also dir of redirects file should be mount.

**Comment by kelson42** [comment]
@dattaz @asashnov I don't really understand the problem here. I is clear that all the paths given are *within the Docker container* and not the one of the master system. The problem is the same for all paths!? To me there is nothing to do except a documentation like I have done for example here https://github.com/kiwix/kiwix-tools/tree/master/docker/server (case is simplier but the same otherwise).

**Comment by kelson42** [comment]
@rgaudin Maybe you have an opinion on that one as I don’t get any feedback?

**Comment by rgaudin** [comment]
I don't see the value of this. I'm not in favor of hiding the VM-nature of docker and the need for volumes. This is unexpected, complicated and will lead to problems and more maintenance. The benefit doesn't match the efforts.
Should one see the need for this, one can write a small script that would do this and invoke docker run. That's be cleaner and simpler.

This tickets is 3y+ old. Should we close it?
