### ISSUE TITLE
Migrate to other command line parser

### ISSUE THREAD

**Issue by data-man** [openzim/zim-tools#240]
Sorry, I really dislike docopt (very limited functionality and no active development).

Let's use https://github.com/CLIUtils/CLI11.

- C++11
- header only (single file ~347 KiB), can be shipped in zim-tools sources
- builtin validators
- subcommands
- and much more!

What do you think?

**Comment by kelson42** [comment]
Strongly against, without a clear problem we won't change this dependence.

**Comment by data-man** [comment]
> Strongly against

Why?
`docopt` used only in `zimdump` and `zimsplit`.

>without a clear problem 

Because it's a bad library.

**Comment by kelson42** [comment]
We never do changes without a clear need.

**Comment by kelson42** [comment]
@veloman-yunkan @mgautierfr Youe feedback is welcome on this ticket.

**Comment by mgautierfr** [comment]
> Because it's a bad library.

Can you be a bit more explicit ?
"I really dislike" it is not a argument.
---

I'm not against a change. CLI11 seems to be a good library, maybe better than docopt.
But it is not because one is better than the other that we MUST change the library.
docopt seems to do the job, why change it ?
Why we should change it (except you dislike it). How it would improve our software or our daily work, maintenance, ...  ?

**Comment by kelson42** [comment]
Closing, at least for the moment, no strong reason to come back on a decision which is just one year old.
