### ISSUE TITLE
Don't check the existing of favicon by zimcheck

### ISSUE THREAD

**Issue by pavel-karatsiuba** [openzim/zim-tools#334]
The specification requires not creating the favicon inside zim file.
Please remove checking of favicon by zimcheck.

Right now zimcheck returns the error:
`[ERROR] Favicon:
Favicon is missing
`

**Comment by veloman-yunkan** [comment]
> The specification requires not creating the favicon inside zim file.

@pavel-karatsiuba Will you please point to the exact location in the specification supporting your statement?

**Comment by kelson42** [comment]
@pavel-karatsiuba Your bug description is not correct

**Comment by kelson42** [comment]
@pavel-karatsiuba A proper formulation is: If in the past `-/Favicon` was a mandatory entry. The very same content (PNG) is now called `M/Illustration_48x48@1` and it is still mandatory. We need:
* To check `M/Illustration_48x48@1` (because this is mandatory)
* Issue a warning if the ZIM is still using the old `-/Favicon`
* Test this properly

@veloman-yunkan We are currently in a middle of an effort to sanitize the ZIM metadata. This has become very necessary as we start to be really better in ZIM generation/management. We run this effort at all levels (specification, libzim, scrapers, zim-tools and other solutions).

Unfortunately the zim-tools are pretty much imperfect (considering this metadata) like the rest of the software stack. Unfortunatley we have scrapers (like MWoffliner) which rely on `zimcheck` in their CI. As a consequence, we need *urgently* to get zimcheck working fine first so we can then improve the scrapers.

But this might be less straight forward than first though. Actually we have a few tickets related to metadata and checking if they are correct, see for example #332 or #336. If we don't want to deal with an endless list of bugs/improvements to do around this we should probably do it right now. I would propose:
* Have a proper table/list of Medata with their properties (like: name, mandatory, max length, value maching regex, ...)
* This list could be used by `zimcheck` to... check...
* This list could be used by `zimwriterfs` to verify the command line arguments
* Woudl be easy to update

What do you think? Would you be able to quickly implement something like this so we can release `3.2.0` and use the latest `zimcheck` in MWoffliner CI?
