### ISSUE TITLE
Removing zimsearch?

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#9]
Is that really necessary? What is articulation with kiwix-search?

It seems also unclear to users, see https://github.com/kiwix/kiwix-tools/issues/130

**Comment by julianharty** [comment]
I certainly agree that the purpose of zimsearch is in question, although presumably it's for the core zimlib library rather than the enhanced kiwix-lib library that offers additional capabilities. To be blunt I don't really understand what either kiwix-search or zimsearch offer, particularly for older ZIM files. That said, I'd love to have a command-line utility that does return results :)

**Comment by mgautierfr** [comment]
I disagree to remove it.
Zim files have a embedded index and `zimSearch` is the only tool to search in it without using a tool from a separated project (`kiwix-search`).

> To be blunt I don't really understand what either kiwix-search or zimsearch offer, particularly for older ZIM files

- `zimsearch` does nothing with older ZIM files as they don't contain search database.
- `kiwix-search` does nothing with older ZIM files as they don't contain search database. (If PR kiwix/kiwix-tools#136 is merged, `kiwix-search` will be able to return suggestions on older ZIM files)
- `kiwix-search` can search on separated xapian database (`.idx` directory) provided with (or generated from) older ZIM files.

**Comment by kelson42** [comment]
@mgautierfr ok, but at the end then `zimSearch` and `kiwix-serarch` will provide the same service?

**Comment by kelson42** [comment]
@mgautierfr Considering that we don't support external index anymore. I would say the third argument is not valid anymore.

**Comment by kelson42** [comment]
I'm finally in favour to keep both. Even if at the end they might be quite similar. We will see.
